需要import的package。
第一个是python的numpy科学计算库，可以将矩阵向量化，避免显示for循环，大幅提升运算速度

In [1]:
import numpy as np

激活函数是每个隐藏层节点和输出层的输出，输入和权重矩阵相乘，加上初始偏置值后，再作为激活函数自变量，映射后进行输出。

relu函数即线性激活函数，定义为：(python中）

In [2]:
# 定义激活函数
def relu(x):
    return np.maximum(x, 0)

除此之外，还有带泄露的relu函数：

（本次运算中，带泄露的relu函数并不会用到）

In [3]:
def relu_2(x):
   
   if x>=0:
     
     return np.maximum(x, 0)
   
   if x>=0:
     
     return np.minimum(0.01*x, 0)

除此之外，还有signoid函数和tanh函数，这两个函数都是为了将输出归一到[-1,1]，同时这两个函数还是非线性函数，事实上只有非线性的输出才能进行拟合。

In [25]:
# 定义神经网络类
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        # 初始化权重和偏置
        self.W1 = np.random.randn(input_size, hidden_size)
        self.b1 = np.random.randn(hidden_size)
        self.W2 = np.random.randn(hidden_size, output_size)
        self.b2 = np.random.randn(output_size)

    def forward(self, X):
        # 前向传播计算
        Z1 = np.dot(X, self.W1) + self.b1
        A1 = relu(Z1)
        Z2 = np.dot(A1, self.W2) + self.b2
        return Z2

    def train(self, X, y, learning_rate=0.01, max_epochs=1000):
        # 训练模型
        for epoch in range(max_epochs):
            # 前向传播计算
            Z1 = np.dot(X, self.W1) + self.b1
            A1 = relu(Z1)
            Z2 = np.dot(A1, self.W2) + self.b2

            # 计算误差
            loss = np.mean((Z2 - y) ** 2)

            # 反向传播更新权重和偏置
            dZ2 = Z2 - y
            dW2 = np.dot(A1.T, dZ2)
            db2 = np.sum(dZ2, axis=0)
            dA1 = np.dot(dZ2, self.W2.T)
            dZ1 = dA1 * (Z1 > 0)
            dW1 = np.dot(X.T, dZ1)
            db1 = np.sum(dZ1, axis=0)

            self.W1 -= learning_rate * dW1
            self.b1 -= learning_rate * db1
            self.W2 -= learning_rate * dW2
            self.b2 -= learning_rate * db2

            if epoch % 500 == 0:
                print("Epoch %d, Loss = %f" % (epoch, loss))
                print(dW1)
                print("\n")
                print(db2)
        return self


In [23]:
# 创建神经网络模型
input_size = 4
hidden_size1 = 5
output_size = 1
model = NeuralNetwork(input_size, hidden_size1,output_size)

# 12组数据作为训练集X和标签y
X_train = np.array([[3, 100, 4, 1], [3, 80, 8, 1], [2, 130, 1, 1], [1, 150, 2, 2], [5, 120, 4, 3],[2,100,4,4],[4,80,2,3],[4,120,2,3], [3,120,2,3], [3,120,5,3], [2,120,5,3], [2,80,5,1]])
y_train = np.array([305.427684, 195.427684, 431.945280, 438.591409, 1127.065795, 861.945280, 587.990750, 707.990750 ,535.427685 ,469.331280, 405.848876, 165.848876]).reshape(-1,1)

# 训练模型
model.train(X_train, y_train, learning_rate=0.001, max_epochs=10000)


Epoch 0, Loss = 224076.673109
[[-1.68128023e+04  0.00000000e+00 -4.85468602e+02  6.66473119e+02
  -2.22290902e+04]
 [-5.85120447e+05  0.00000000e+00 -1.68953159e+04  2.31946491e+04
  -7.73618518e+05]
 [-1.73160112e+04  0.00000000e+00 -4.99998727e+02  6.86420728e+02
  -2.28944092e+04]
 [-1.46910607e+04  0.00000000e+00 -4.24203447e+02  5.82365561e+02
  -1.94238240e+04]]


[-5198.29130824     0.          -150.1003325    206.06448354
 -6872.93435043]
Epoch 500, Loss = 1200806.463200
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[0. 0. 0. 0. 0.]
Epoch 1000, Loss = 69376.693218
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[0. 0. 0. 0. 0.]
Epoch 1500, Loss = 69370.228164
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[0. 0. 0. 0. 0.]
Epoch 2000, Loss = 69370.228127
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[0. 0. 0. 0. 0.]
Epoch 2500, Loss = 69370.228127
[[0. 0. 0. 0. 0.]
 [

In [28]:
# 预测房价
X_test = np.array([1, 100, 3, 5])
y_pred = model.forward(X_test)
rate=y_pred/261.945280
print(y_pred)

[519.40344575]
